#!/bin/sh
case "$1" in
	bound)
		ifconfig "$interface" "$ip" netmask "$subnet"
		route add default gw "$router"
		echo -n > /etc/resolv.conf
		[ "$dns" != "" ] && echo nameserver "$dns" >> /etc/resolv.conf
		[ -f /etc/resolv.conf.tail ] && cat /etc/resolv.conf.tail >> /dev/resolv.conf
		;;
	deconfig)
		echo -n > /etc/resolv.conf
		route del default 2> /dev/null
		ifconfig "$interface" default
		;;
esac

