#!/bin/sh
echo "Starting Toyroot ..."

echo "Mounting filesystems ..."
mountpoint -q /dev || mount -n /dev
mknod /dev/root b "`mountpoint -dq / | cut -d : -f 1`" "`mountpoint -dq / | cut -d : -f 2`"
chmod 600 /dev/root
mount -n -o remount /
mount -n /proc
[ "`readlink /etc/mtab`" = /proc/mounts ] || echo -n > /etc/mtab
mount -o remount /
[ -e /dev/pts ] && rm -fr /dev/pts
[ -e /dev/shm ] && rm -fr /dev/shm
mkdir -p /dev/pts
mkdir -p /dev/shm
mount -f /dev
mount -f /proc
mount -a

echo "Preparing filesystems ..."
if [ -e /dev/fb0 ]; then
	chown root:weston-launch /dev/fb0
	chmod 660 /dev/fb0
fi
if [ "`readlink /etc/mtab`" = /proc/mounts ]; then
	mkdir -p /var/etc /var/db /var/run /var/tmp
	echo -n > /var/etc/resolv.conf
fi

echo "Setting hostname ..."
[ -e /etc/hostname ] && hostname "`cat /etc/hostname`"

for file in `ls /etc/rc.d/S*`; do
	"$file" start
done
