#!/bin/sh

. /etc/network.conf

case "$1" in
	start)
		echo "Starting network ..."
		[ "$READ_ONLY" = true ] && echo -n > /var/etc/resolv.conf
		ifconfig lo 127.0.0.0 netmask 255.0.0.0 up
		if [ "$INTERFACE" != "" ]; then
			if [ "$ADDRESS" != "" -a "$DHCP" != yes -a "$DHCP" != true ]; then
				ifconfig "$INTERFACE" "$ADDRESS" netmask "$NETMASK" up
				sleep 1
				route add default gw "$GATEWAY"
				echo -n > /etc/resolv.conf
				[ -f /etc/resolv.conf.static ] && cat /etc/resolv.conf.static >> /etc/resolv.conf
				[ -f /etc/resolv.conf.tail ] && cat /etc/resolv.conf.tail >> /etc/resolv.conf
			else
				dhclient "$INTERFACE"
			fi
		fi
		;;
	stop)
		echo "Stopping network ..."
		if [ "$INTERFACE" != "" ]; then
			if [ -f /var/run/dhclient.pid ]; then
				dhclient -r
				rm -f /var/run/dhclient.pid
			else
				echo -n > /etc/resolv.conf
				route del default gw "$GATEWAY"
				ifconfig "$INTERFACE" down
			fi
		fi
		ifconfig lo down
		;;
esac
