[ -f Makefile ] && make clean
CC="$MUSL_GCC" CXX="$GXX_UC" CFLAGS="$PKG_CFLAGS" CXXFLAGS="$PKG_CFLAGS" LDFLAGS="$PKG_LDFLAGS" LIBS="$PKG_LIBS $PKG_GLIB_LIBS $PKG_ATK_LIBS $PKG_PANGO_LIBS $PKG_CAIRO_GOBJECT_LIBS $PKG_GDK_PIXBUF_LIBS $PKG_WAYLAND_LIBS $PKG_LIBXKBCOMMON_LIBS $PKG_DEP_GLIB_LIBS $PKG_DEP_ATK_LIBS $PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_GOBJECT_LIBS $PKG_DEP_GDK_PIXBUF_LIBS" STRIP="$STRIP" \
BASE_DEPENDENCIES_CFLAGS="$PKG_DEP_GLIB_CFLAGS $PKG_DEP_ATK_CFLAGS $PKG_DEP_PANGO_CFLAGS $PKG_DEP_CAIRO_GOBJECT_CFLAGS $PKG_DEP_GDK_PIXBUF_CFLAGS" \
BASE_DEPENDENCIES_LIBS="$PKG_DEP_GLIB_LIBS $PKG_DEP_ATK_LIBS $PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_GOBJECT_LIBS $PKG_DEP_GDK_PIXBUF_LIBS" \
CAIRO_BACKEND_CFLAGS="$PKG_DEP_CAIRO_GOBJECT_CFLAGS" \
CAIRO_BACKEND_LIBS="$PKG_DEP_CAIRO_GOBJECT_LIBS" \
GDK_DEP_CFLAGS="$PKG_DEP_GLIB_CFLAGS $PKG_DEP_PANGO_CFLAGS $PKG_DEP_CAIRO_CFLAGS $PKG_DEP_GDK_PIXBUF_CFLAGS $PKG_DEP_WAYLAND_CFLAGS $PKG_DEP_LIBXKBCOMMON_CFLAGS" \
GDK_DEP_LIBS="$PKG_DEP_GLIB_LIBS $PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_LIBS $PKG_DEP_GDK_PIXBUF_LIBS $PKG_DEP_WAYLAND_CLIENT_LIBS $PKG_DEP_WAYLAND_CURSOR_LIBS $PKG_DEP_LIBXKBCOMMON_LIBS" \
ATK_CFLAGS="$PKG_DEP_ATK_CFLAGS" \
ATK_LIBS="$PKG_DEP_ATK_CFLAGS" \
GTK_DEP_CFLAGS="$PKG_DEP_GLIB_CFLAGS $PKG_DEP_ATK_CFLAGS $PKG_DEP_PANGO_CFLAGS $PKG_DEP_CAIRO_GOBJECT_CFLAGS $PKG_DEP_GDK_PIXBUF_CFLAGS" \
GTK_DEP_LIBS="$PKG_DEP_GLIB_LIBS $PKG_DEP_ATK_LIBS $PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_GOBJECT_LIBS $PKG_DEP_GDK_PIXBUF_LIBS" \
GMODULE_CFLAGS="$PKG_DEP_GLIB_CFLAGS" \
GMODULE_LIBS="$PKG_DEP_GLIB_GMODULE_LIBS" \
WAYLAND_SCANNER="$ROOT_DIR/build/$ARCH/wayland/wayland-host/wayland-scanner" \
./configure --host="$TARGET" --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-wayland-backend --without-x && make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME" GLIB_MKENUMS=glib-mkenums GLIB_GENMARSHAL=glib-genmarshal GLIB_COMPILE_RESOURCES=glib-compile-resources
STATUS=$?
if [ $STATUS = 0 ]; then
	[ -d "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gtk-3.0/3.0.0/immodules" ] && rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gtk-3.0/3.0.0/immodules"/*.la
	[ -d "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gtk-3.0/3.0.0/printbackends" ] && rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gtk-3.0/3.0.0/printbackends"/*.la
	if [ -d "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/share/glib-2.0/schemas" ]; then
		rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/share/glib-2.0/schemas"/*.compiled
		glib-compile-schemas "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/share/glib-2.0/schemas"
	fi
fi
[ $STATUS = 0 ]
