[ -f Makefile ] && make clean
CC="$MUSL_GCC" CXX="$GXX_UC" CFLAGS="$PKG_CFLAGS $PKGCFG_FREETYPE_CFLAGS" CXXFLAGS="$PKG_CFLAGS $PKGCFG_FREETYPE_CFLAGS" LDFLAGS="$PKG_LDFLAGS" LIBS="$PKG_LIBS $PKG_FREETYPE_LIBS $PKG_GLIB_GLIB_LIBS $PKG_GLIB_GOBJECT_LIBS $PKG_CAIRO_LIBS $PKGCFG_FREETYPE_LIBS" STRIP="$STRIP" \
GLIB_CFLAGS="$PKGCFG_GLIB_CFLAGS" \
GLIB_LIBS="$PKGCFG_GLIB_GLIB_LIBS" \
GOBJECT_CFLAGS="$PKGCFG_GLIB_CFLAGS" \
GOBJECT_LIBS="$PKGCFG_GLIB_GOBJECT_LIBS" \
CAIRO_CFLAGS="$PKGCFG_CAIRO_CFLAGS" \
CAIRO_LIBS="$PKGCFG_CAIRO_LIBS" \
./configure --host="$TARGET" --prefix=/usr --sysconfdir=/etc --localstatedir=/var && make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME"
