[ -f Makefile ] && make clean
CC="$MUSL_GCC" CFLAGS="$PKG_CFLAGS $PKG_GTKX_CFLAGS $PKG_LIBCROCO_CFLAGS $PKG_DEP_GTKX_CFLAGS" LDFLAGS="$PKG_LDFLAGS" LIBS="$PKG_LIBS $PKG_GTKX_LIBS $PKG_LIBCROCO_LIBS $PKG_DEP_GTKX_LIBS $PKG_DEP_LIBCROCO_LIBS" STRIP="$STRIP" \
LIBRSVG_CFLAGS="$PKG_DEP_GLIB_CFLAGS $PKG_DEP_PANGO_CFLAGS $PKG_DEP_CAIRO_GOBJECT_CFLAGS $PKG_DEP_LIBCROCO_CFLAGS" \
LIBRSVG_LIBS="$PKG_DEP_GLIB_LIBS $PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_GOBJECT_LIBS $PKG_DEP_LIBCROCO_LIBS" \
RSVG_CONVERT_CFLAGS="$PKG_DEP_PANGO_CFLAGS $PKG_DEP_CAIRO_GOBJECT_CFLAGS $PKG_DEP_LIBCROCO_CFLAGS" \
RSVG_CONVERT_LIBS="$PKG_DEP_PANGO_LIBS $PKG_DEP_CAIRO_GOBJECT_CFLAGS $PKG_DEP_LIBCROCO_LIBS" \
./configure --host="$TARGET" --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-introspection && make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME" gdk_pixbuf_binarydir=/usr/lib/gdk-pixbuf-2.0/2.10.0/ gdk_pixbuf_cache_file=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache gdk_pixbuf_moduledir=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders
STATUS=$?
[ $STATUS = 0 ] && rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"/*.la
[ $STATUS = 0 ]
