[ -f Makefile ] && make clean
CC="$MUSL_GCC" CFLAGS="$PKG_CFLAGS -I$ROOT_DIR/bin/$ARCH/glib_dev/usr/include/glib-2.0 -I$ROOT_DIR/bin/$ARCH/glib_dev/usr/include/gio-unix-2.0 -I$ROOT_DIR/bin/$ARCH/glib_dev/usr/lib/glib-2.0/include -I$ROOT_DIR/bin/$ARCH/gdk-pixbuf_dev/usr/include/gdk-pixbuf-2.0 -I$ROOT_DIR/bin/$ARCH/libxml2_dev/usr/include/libxml2" LDFLAGS="$PKG_LDFLAGS" LIBS="$PKG_LIBS -lcroco-0.6 -lxml2 -lgmodule-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -latk-1.0 -lpango-1.0 -lpangocairo-1.0 -lpangoft2-1.0 -lcairo -lcairo-gobject -lcairo-script-interpreter -lgdk_pixbuf-2.0 -lharfbuzz -lfontconfig -lfreetype -ltiff -lpixman-1 -ljpeg -lpng -lffi -lexpat -llzma -lbz2 -lz -lwayland-client -lwayland-cursor -lxkbcommon" STRIP="$STRIP" \
LIBRSVG_CFLAGS="-I$ROOT_DIR/bin/$ARCH/glib_dev/usr/include/glib-2.0 -I$ROOT_DIR/bin/$ARCH/glib_dev/usr/lib/glib-2.0/include -I$ROOT_DIR/bin/$ARCH/pango_dev/usr/include/pango-1.0 -I$ROOT_DIR/bin/$ARCH/cairo_dev/usr/include/cairo -I$ROOT_DIR/bin/$ARCH/libcroco_dev/usr/include/libcroco-0.6" \
LIBRSVG_LIBS="-L$ROOT_DIR/bin/$ARCH/glib/usr/lib -L$ROOT_DIR/bin/$ARCH/glib_dev/usr/lib -L$ROOT_DIR/bin/$ARCH/pango/usr/lib -L$ROOT_DIR/bin/$ARCH/pango_dev/usr/lib -L$ROOT_DIR/bin/$ARCH/cairo/usr/lib -L$ROOT_DIR/bin/$ARCH/cairo_dev/usr/lib -L$ROOT_DIR/bin/$ARCH/libcroco/usr/lib -L$ROOT_DIR/bin/$ARCH/libcroco_dev/usr/lib -lgmodule-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpango-1.0 -lpangocairo-1.0 -lcairo -lcairo-gobject -lcairo-script-interpreter -lcroco-0.6" \
RSVG_CONVERT_CFLAGS="-I$ROOT_DIR/bin/$ARCH/pango_dev/usr/include/pango-1.0 -I$ROOT_DIR/bin/$ARCH/cairo_dev/usr/include/cairo" \
RSVG_CONVERT_LIBS="-L$ROOT_DIR/bin/$ARCH/pango/usr/lib -L$ROOT_DIR/bin/$ARCH/pango_dev/usr/lib -L$ROOT_DIR/bin/$ARCH/cairo/usr/lib -L$ROOT_DIR/bin/$ARCH/cairo_dev/usr/lib -lpango-1.0 -lpangocairo-1.0 -lcairo -lcairo-gobject -lcairo-script-interpreter" \
./configure --host="$TARGET" --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-introspection && make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME" gdk_pixbuf_binarydir=/usr/lib/gdk-pixbuf-2.0/2.10.0/ gdk_pixbuf_cache_file=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache gdk_pixbuf_moduledir=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders
STATUS=$?
[ $STATUS = 0 ] && rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"/*.la
[ $STATUS = 0 ]
