[ -f Makefile ] && make clean
CC="$MUSL_GCC" CFLAGS="$PKG_CFLAGS $PKG_FONTCONFIG_CFLAGS" LDFLAGS="$PKG_LDFLAGS" LIBS="$PKG_LIBS $PKG_FREETYPE_LIBS $PKG_FONTCONFIG_LIBS $PKG_HARFBUZZ_LIBS $PKG_GLIB_LIBS" STRIP="$STRIP" \
CAIRO_CFLAGS="$PKG_DEP_CAIRO_CFLAGS" \
CAIRO_LIBS="$PKG_DEP_CAIRO_LIBS" \
FREETYPE_CFLAGS="$PKG_DEP_FREETYPE_CFLAGS" \
FREETYPE_LIBS="$PKG_DEP_FREETYPE_LIBS" \
FONTCONFIG_CFLAGS="$PKG_DEP_FONTCONFIG_CFLAGS" \
FONTCONFIG_LIBS="$PKG_DEP_FONTCONFIG_LIBS" \
HARFBUZZ_CFLAGS="$PKG_DEP_HARFBUZZ_CFLAGS" \
HARFBUZZ_LIBS="$PKG_DEP_HARFBUZZ_LIBS" \
GLIB_CFLAGS="$PKG_DEP_GLIB_CFLAGS" \
GLIB_LIBS="$PKG_DEP_GLIB_LIBS" \
./configure --host="$TARGET" --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-symbol-lookup --without-xft && make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME"
STATUS=$?
[ $STATUS = 0 ] && rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/pango-1.8.0/modules"/*.la
[ $STATUS = 0 ]
