[ -f Makefile ] && make clean
CC="$MUSL_GCC" CFLAGS="$PKG_CFLAGS $PKG_CAIRO_CFLAGS $PKGCFG_PIXMAN_CFLAGS $PKGCFG_GLIB_CFLAGS" LDFLAGS="$PKG_LDFLAGS $PKG_CAIRO_LDFLAGS" LIBS="$PKG_LIBS $PKG_WAYLAND_LIBS $PKG_CAIRO_LIBS $PKG_PANGO_LIBS -lxkbcommon" STRIP="$STRIP" \
COMPOSITOR_CFLAGS="$PKGCFG_WAYLAND_CFLAGS $PKGCFG_PIXMAN_CFLAGS" \
COMPOSITOR_LIBS="$PKGCFG_WAYLAND_SERVER_LIBS $PKGCFG_PIXMAN_LIBS" \
RPI_COMPOSITOR_CFLAGS="$PKGCFG_MTDEV_CFLAGS $PKGCFG_EUDEV_CFLAGS" \
RPI_COMPOSITOR_LIBS="$PKGCFG_MTDEV_LIBS $PKGCFG_EUDEV_LIBS" \
FBDEV_COMPOSITOR_CFLAGS="$PKGCFG_MTDEV_CFLAGS $PKGCFG_EUDEV_CFLAGS" \
FBDEV_COMPOSITOR_LIBS="$PKGCFG_MTDEV_LIBS $PKGCFG_EUDEV_LIBS" \
PIXMAN_CFLAGS="$PKGCFG_PIXMAN_CFLAGS" \
PIXMAN_LIBS="$PKGCFG_PIXMAN_LIBS" \
CAIRO_CFLAGS="$PKGCFG_CAIRO_CFLAGS" \
CAIRO_LIBS="$PKGCFG_CAIRO_LIBS" \
TEST_CLIENT_CFLAGS="$PKGCFG_WAYLAND_CFLAGS" \
TEST_CLIENT_LIBS="$PKGCFG_WAYLAND_CLIENT_LIBS" \
SIMPLE_CLIENT_CFLAGS="$PKGCFG_WAYLAND_CFLAGS" \
SIMPLE_CLIENT_LIBS="$PKGCFG_WAYLAND_CLIENT_LIBS" \
CLIENT_CFLAGS="$PKGCFG_WAYLAND_CFLAGS $PKGCFG_CAIRO_CFLAGS $PKGCFG_LIBXKBCOMMON_CFLAGS" \
CLIENT_LIBS="$PKGCFG_WAYLAND_CLIENT_LIBS $PKGCFG_WAYLAND_CURSOR_LIBS $PKGCFG_CAIRO_LIBS $PKGCFG_LIBXKBCOMMON_LIBS" \
SERVER_CFLAGS="$PKGCFG_WAYLAND_CFLAGS" \
SERVER_LIBS="$PKGCFG_WAYLAND_SERVER_LIBS" \
WESTON_INFO_CFLAGS="$PKGCFG_WAYLAND_CFLAGS" \
WESTON_INFO_LIBS="$PKGCFG_WAYLAND_CLIENT_LIBS" \
WCAP_CFLAGS="$PKGCFG_CAIRO_CFLAGS" \
WCAP_LIBS="$PKGCFG_CAIRO_LIBS" \
wayland_scanner="$ROOT_DIR/build/$ARCH/wayland/wayland-host/wayland-scanner" \
WAYLAND_SCANNER_CFLAGS="$PKGCFG_WAYLAND_CFLAGS" \
WAYLAND_SCANNER_LIBS="$PKGCFG_WAYLAND_SERVER_LIBS" \
PNG_CFLAGS="$PKGCFG_LIBPNG_CFLAGS" \
PNG_LIBS="$PKGCFG_LIBPNG_LIBS" \
PANGO_CFLAGS="$PKGCFG_PANGO_CFLAGS" \
PANGO_LIBS="$PKGCFG_PANGO_LIBS" \
./configure \
	--host="$TARGET" \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--disable-egl \
	--disable-libunwind \
	--disable-xwayland \
	--disable-x11-compositor \
	--disable-drm-compositor \
	--disable-wayland-compositor \
	--disable-headless-compositor \
	--disable-libinput-backend \
	--enable-demo-clients-install \
&& make install DESTDIR="$ROOT_DIR/bin/$ARCH/$PKG_NAME"
STATUS=$?
if [ $STATUS = 0 ]; then
	[ "`ls "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/share/man/man7"`" = "" ] && rmdir "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/share/man/man7"
	rm -f "$ROOT_DIR/bin/$ARCH/$PKG_NAME/usr/lib/weston"/*.la
fi
[ $STATUS = 0 ]
